{% set data = load_setup_py_data() %}

package:
  name: integration
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/integration.git

build:
  number: 0
  script: python -m pip install . -vv
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:  # your library dependencies
    - python
    # - jupyter
    # - ipython
    # - matplotlib>=3.0
    # - numpy>=1.1
    # - requests
    # - biopython
    # - goatools>=1.2
    # - pytables
    # - wget

channels:  # channels for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  - conda-verify
  
test:
  imports:
    - integration

about:
  home: https://github.com/munch-group/integration.git
  license: MIT
  dev_url: https://github.com/munch-group/integration.git
  doc_url: https://munch-group.org/integration
